// ══════════════════════════════════════════════════════════
//  FIREBASE CONFIG & APP CONSTANTS
// ══════════════════════════════════════════════════════════

export const firebaseConfig = {
  apiKey: "AIzaSyCwbHSfLk9mF1DdShfeOeuZ32swk6qAdqc",
  authDomain: "eventmanagement-2a30a.firebaseapp.com",
  projectId: "eventmanagement-2a30a",
  storageBucket: "eventmanagement-2a30a.firebasestorage.app",
  messagingSenderId: "620682387906",
  appId: "1:620682387906:web:56f684258fd5a95c50f65b",
  measurementId: "G-RQHJGK65RS"
};

export const APP = {
  name:    "Eventify",
  tagline: "Your all-in-one workspace for creating, managing, and tracking events — beautifully.",
  features: [
    { icon: "fa-calendar-check",  text: "Create & manage events effortlessly" },
    { icon: "fa-magnifying-glass", text: "Powerful search & category filters"  },
    { icon: "fa-cloud",            text: "Synced across all your devices"       },
  ],
  categories: [
    { id: "conference", label: "Conference",  icon: "fa-microphone-lines" },
    { id: "social",     label: "Social",      icon: "fa-champagne-glasses" },
    { id: "workshop",   label: "Workshop",    icon: "fa-chalkboard-user"  },
    { id: "webinar",    label: "Webinar",     icon: "fa-desktop"          },
    { id: "sports",     label: "Sports",      icon: "fa-trophy"           },
    { id: "other",      label: "Other",       icon: "fa-tag"              },
  ],
  colors: [
    { hex: "#4f7cff", name: "Blue"   },
    { hex: "#6c5ce7", name: "Purple" },
    { hex: "#ff6b6b", name: "Red"    },
    { hex: "#f6a623", name: "Orange" },
    { hex: "#2ec27e", name: "Green"  },
    { hex: "#e91e8c", name: "Pink"   },
    { hex: "#00b4d8", name: "Cyan"   },
    { hex: "#1a1a2e", name: "Dark"   },
  ],
  categoryColors: {
    conference: { bg: "rgba(108,92,231,.12)", color: "#6c5ce7" },
    social:     { bg: "rgba(246,166,35,.12)", color: "#d97706" },
    workshop:   { bg: "rgba(46,194,126,.12)", color: "#16a34a" },
    webinar:    { bg: "rgba(0,180,216,.12)",  color: "#0284c7" },
    sports:     { bg: "rgba(255,107,107,.12)",color: "#dc2626" },
    other:      { bg: "rgba(107,107,130,.12)",color: "#6b6b82" },
  },
  strings: {
    loginHeading:    "Welcome back",
    loginSub:        "Sign in to manage your events",
    googleBtn:       "Continue with Google",
    divider:         "No account needed",
    loginInfo:       "Sign in with your Google account to get started. Your events are saved securely and accessible from any device.",
    loginNote:       "By continuing, you agree to our Terms of Service and Privacy Policy.",
    navMain:         "Main",
    navDashboard:    "Dashboard",
    navUpcoming:     "Upcoming",
    navPast:         "Past Events",
    navCategories:   "Categories",
    create:          "New Event",
    searchPH:        "Search events…",
    allEvents:       "All Events",
    upcomingEvents:  "Upcoming Events",
    pastEvents:      "Past Events",
    emptyTitle:      "No events yet",
    emptyMsg:        "Create your first event and it will show up right here.",
    emptySearch:     "No results found",
    emptySearchMsg:  "Try adjusting your search or filter.",
    signOut:         "Sign Out",
    account:         "Account",
    totalEvents:     "Total Events",
    upcomingCount:   "Upcoming",
    pastCount:       "Past Events",
    categoriesCount: "Categories",
    eventsManaged:   "events managed",
    deleteTitle:     "Delete Event?",
    deleteMsg:       "This action cannot be undone. The event will be permanently removed.",
    deleteBtn:       "Delete",
    cancelBtn:       "Cancel",
    createModal:     "Create Event",
    editModal:       "Edit Event",
    saveBtn:         "Save Event",
    lbl_title:       "Event Title",
    lbl_desc:        "Description",
    lbl_date:        "Date",
    lbl_time:        "Time",
    lbl_location:    "Location",
    lbl_category:    "Category",
    lbl_color:       "Color Theme",
    lbl_attendees:   "Expected Attendees",
    ph_title:        "Give your event a name…",
    ph_desc:         "What's this event about?",
    ph_location:     "Venue or online link",
    ph_attendees:    "0",
    toastCreated:    "Event created!",
    toastUpdated:    "Event updated!",
    toastDeleted:    "Event deleted.",
    toastSignout:    "Signed out successfully.",
    gridView:        "Grid view",
    listView:        "List view",
    filterAll:       "All",
  }
};
